language: php
php:
- 5.6
addons:
  ssh_known_hosts: 
env:
  global:
  - secure: d43kAf+XCLMOABEVY8RcyC50xJ9P8YpwQVR6NNVzfLATTEQiZanQK8KHBHQ5uFcWrzArFYaC8r4trqHuwr68XXBFXyjX+tyrCOadMMIQKszjfHUXbD9EnV7YtQ5/qt8+htgjj0KNtrYLsUs30KJLQBYCnnBavHKgDZ+YjK2i+ySjUJVIvxlf+3zbmM5LPYNPdCcRqisp9C4G/90zllNzeGkkhaRKYfxpeNGuR5uB96N0Aowqjdd4edoZww3ghELt/RyXwhHc+mQkrPczETODxB2BLAroneYPqMEXvvxCU4bYafJc/Pv+JK0Wrjtn2hMLx/k6YXA7GeKCkuIsvHQRWClFfoO0wIgrofnOZ/gPWS5dkHEcHXK0Mk1Es66orXZAYCwrHy2Lvsadtj86bvm+bPTR7IbAQpmYc5jRn0RbJWz9TWmpbXBBRtgUv8OOFwXpQie0hClWzgPKrH0oSLRWoC188AyFD2AELAqZzY8mYgehXXUS+MwQexmpuVA812KHCbhoPaWz91H/RhjK3Xs5++RlhoM9jfHArXmZpTUzTC4OWLzgxdhwK7UTJKBIk+F0H88RfFy3WsngLwp/E0Jj9ki/A201GkYlCIl9u9N+GexLKq2oE81OEuLsLnXZ6y+sHMol8J2T2btRzHBr8sCp2iwUbRqNobSMMgTxD0ZZ/nY=
  - secure: G/qEeT5H0n0ycq4/H4mCC4vS1Ugr5X4IQFSxnt7M4/USweaePWOd+KS/OBUB0iecLeQDk8t0HLt476NU/XQhMRMPqLZfE7fM2/x5601XOwXPfLGQoeO2x5imfE4VR62IZ7B4CKgl36o7zQcYNaGNo1PnESlJLImtbLyJ4bjRr7sMKAHMgEJ/7DxhRECnslh/tvBuys01I/NGm27tRn62y1dsr3qMBgbPuWQMCIbBLkDaTqEdRIL31IFex0wf9NaRfHPjHbULrxunxRiU810AQ+iblX60J8x8qtMUuP2W1feO0irAVvLJJAhS+40l5HY9vpuYyxlxNyxbfMl9ep8gzak+H3PUgaibG7SvbwfCDRr3ox9WnrmbbXde1Yav6vqllV9M8tKceJtSTeRRohfw9Z7IjTnAhceYGtO1jLc0WtArmiRyyl0wA8F8ENlk4SvL8y9yxZt2SEvpw10JwOSIB0E3O06IvbOPLxn/Aimxe6DnblB0cFJrNMf+XgDLShjxy1nRSYhNt/Epr81hEPzXTdZ+NW5YF5Q5o+pzeXJo0//Q+PmDZ7ZNp/RAC3LiBQ4t8Df0Yt9KPptk+b0Qda4tlcIhY19qLOlpBP18XBzzD0c7m0AC9keftX46mVnzbVFPVyRd+Lrkj1VWtNprjoMEgKLj92oShlnMMoP5whlpIgA=
before_script:
- composer install
script: phpunit --configuration tests/phpunit.xml
deploy:
  provider: s3
  access_key_id: $aa
  secret_access_key: $bb
  bucket: 247travis-react
  skip_cleanup: true
