language: php
php:
- 5.6
addons:
  ssh_known_hosts: 
before_script:
- composer install
script: phpunit --configuration tests/phpunit.xml
deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACESS_KEY"
  bucket: 247travis-react
env:
  global:
  - secure: vW6j2T6mW0eshjsy++UTMZWmO6u/lbCwv2y2vNTdsH4DEeMXDXO8NS1zwQxmHD+OMpddh0maYdRNumf4w4ENKsjPJvfJwZeFouQKA5AM2WOsTrMU0aNnhvGQh/MNC5/4reePaoV+hnuYgEr9Bd6b3Fr4dlrJU+W2bYOlAQyem/59USk/qsrt4WUqBREn7vifkDiRIqTVH8YEK3Ca9Es8LWOlB3HfT70qIBMequScrGGrUEAtc/JcR3lsQRmosAu7jfzTrCo/0b8A5MUtlZ434quaCb9HdVZh2x3PbWj/UesqiPrtn+itzw6QvYDjyAH5sw6+1E6ftIZ2c7slUc+UaPmgSFiWHsN8R+Och6VEUOYbuXM7ZgU5UcgFfNVBVGtYUYCJH0xohD/TmHSpl6jTdiMhdK2N9UxWNfWCYrQgP1pKI2b/fK+ITUTf5trycqRTHQIbV9Ui3hz0JBQMT2sC9DI3s9XJNjGjLLpczSS6pxj1W1ydlNppuE+TIPIunumV2mVrB3dmtYVUD0n7FP8ZAjPt83X3anSk6V3PBEWejEDoDYZsM2vWJpBo3A4ZhZAd0wKRkyhVJBWYVtrY4EX6uTcJMScqJ5E1W32up47zHGei8vZmIG3X2IiAiNNTnLgjWiHTlEzZRrgkpA31iZPJuRDY9lG8nfyuz+49Ps50KF4=
  - secure: eoe+P6wfPf4NsgJL95zhLdD73XxlSxVQimpqOJGUKPyoCoWeInRBNXpDQsLqKYFyg4bulgPFma9cLuJVSa0yGOJ2dx4ge5otoc1OuDKTJca3AYi6fzKcDn15yv1roj794q2W1DtNETxk0fOvP1Soogvh+FNhmpCHcGArfHz6FVgR/LaKq2i4+t70yrvMbAjnWlQEcsWBvYKO/gfcNi7a8Uzrchw8ay949nulRDYuul6W9FuU35mflODiLunXo79ol0MjwgtxRgFzb/ybVHxY4f4as1knEjfZi0da1eNgWUrRc0kdQhOW/pv2rwrpaToJOBt0Lu0aBLOsJmfiGGPkRSpcSPbdGVkcZLQb74i3VzmP/joUe1n9NwSWLQrEziiW14/CRpp/K9KzE+QYBts8QYuPaw7rcvlxG4dH76kJVmnIQOGq4IDazLZVVz9xMME8rT6z+XTy8eNHe6Q5UtjYTPyKxgVck7SAl6Ym5DEdXcv2skXudr3Q5kZbT6SOqEulFMlVM6MUb9EYS4mzixFTasJvSYrQd3wzwaUq55FxqaBK0Y/z+PqsZlYUisv9FNKU7IuXQizF9uFSFSXhYUzKen7ETz6mjNdfb5BSv3ZkYoxejiAZ9tqw8P54fATNOqM8spE0appE6q/Oq2Z+or5nqCPmMbkV8R+CZ50GpOz+j1w=
